import type { Metadata } from 'next';
import { Geist_Mono, Poppins, Roboto_Condensed } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { Providers } from '@/components/providers';
import Navbar from '@/components/navbars/navbar';

const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin', 'latin-ext'],
  variable: '--font-poppins'
});

const robotoCondensed = Roboto_Condensed({
  subsets: ['latin'],
  variable: '--font-roboto-condensed'
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning // react checks if server & client html match, but next-themes changes the theme on the client, so this is needed to avoid a hydration error
      className={cn(
        'h-full',
        'antialiased',
        poppins.variable,
        robotoCondensed.variable,
        geistMono.variable,
        'font-sans'
      )}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
